CREATE TABLE growth_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(2000),
    category VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    priority INTEGER NOT NULL,
    due_date DATE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_growth_tasks_category CHECK (
        category IN ('LEARNING', 'FEATURE', 'TEST', 'DOCUMENTATION', 'REFACTOR', 'SECURITY', 'OPERATIONS')
    ),
    CONSTRAINT chk_growth_tasks_status CHECK (status IN ('TODO', 'IN_PROGRESS', 'DONE')),
    CONSTRAINT chk_growth_tasks_priority CHECK (priority BETWEEN 1 AND 5)
);

CREATE INDEX idx_growth_tasks_status ON growth_tasks (status);
CREATE INDEX idx_growth_tasks_category ON growth_tasks (category);
CREATE INDEX idx_growth_tasks_due_date ON growth_tasks (due_date);
