CREATE TABLE task_progress_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    percent INTEGER NOT NULL,
    note VARCHAR(500),
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_task_progress_entries_task
        FOREIGN KEY (task_id) REFERENCES growth_tasks (id) ON DELETE CASCADE,
    CONSTRAINT chk_task_progress_entries_percent
        CHECK (percent >= 0 AND percent <= 100)
);

CREATE INDEX idx_task_progress_entries_task_recorded
    ON task_progress_entries (task_id, recorded_at DESC, id DESC);
