CREATE TABLE task_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    CONSTRAINT uk_task_tags_name UNIQUE (name)
);

CREATE TABLE growth_task_tags (
    task_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (task_id, tag_id),
    CONSTRAINT fk_growth_task_tags_task FOREIGN KEY (task_id) REFERENCES growth_tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_growth_task_tags_tag FOREIGN KEY (tag_id) REFERENCES task_tags (id) ON DELETE RESTRICT
);

CREATE INDEX idx_growth_task_tags_tag_id ON growth_task_tags (tag_id);
