CREATE TABLE task_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    action VARCHAR(32) NOT NULL,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(2000),
    category VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    priority INTEGER NOT NULL,
    due_date DATE,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_task_audit_logs_action
        CHECK (action IN ('CREATE', 'UPDATE', 'STATUS_CHANGE', 'DELETE'))
);

CREATE INDEX idx_task_audit_logs_task_id
    ON task_audit_logs (task_id, id);
