CREATE TABLE task_time_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    duration_minutes INTEGER NOT NULL,
    note VARCHAR(500),
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_task_time_entries_task
        FOREIGN KEY (task_id) REFERENCES growth_tasks (id) ON DELETE CASCADE,
    CONSTRAINT chk_task_time_entries_duration
        CHECK (duration_minutes > 0)
);

CREATE INDEX idx_task_time_entries_task_recorded
    ON task_time_entries (task_id, recorded_at DESC, id DESC);
