CREATE TABLE dashboard_widget_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dashboard_key VARCHAR(64) NOT NULL,
    widget_type VARCHAR(64) NOT NULL,
    widget_size VARCHAR(16) NOT NULL,
    display_order INTEGER NOT NULL,
    CONSTRAINT uk_dashboard_widget_type UNIQUE (dashboard_key, widget_type),
    CONSTRAINT uk_dashboard_widget_order UNIQUE (dashboard_key, display_order),
    CONSTRAINT chk_dashboard_widget_size CHECK (widget_size IN ('SMALL', 'MEDIUM', 'LARGE')),
    CONSTRAINT chk_dashboard_widget_order CHECK (display_order >= 0)
);

CREATE INDEX idx_dashboard_widget_preferences_dashboard
    ON dashboard_widget_preferences (dashboard_key, display_order);
